FROM ubuntu:latest

################################################# ENV Vars
ENV TZ="America/Argentina/Buenos_Aires"
ENV DEBIAN_FRONTEND=noninteractive
ARG USERNAME=user
ENV USER_UID=1000
ENV USER_GID=$USER_UID



# install pip3
RUN pip3 install ansible \
  ansible[azure] \
  ansible[amazon] \
  ansible[google.cloud] \
  boto3 \
  botocore \
  colorama \
  # locust \
  kubernetes \
  airflow-python-sdk \
  tabulate

RUN ansible-galaxy collection install community.kubernetes


SHELL ["/bin/bash", "-c"]


########################################################
# Install sudo
RUN groupadd --gid $USER_GID $USERNAME ;\
  useradd --uid $USER_UID --gid $USER_GID -m $USERNAME ;\
  echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME ;\
  chmod 0440 /etc/sudoers.d/$USERNAME

COPY p10k.zsh /tmp/p10k.zsh

USER $USERNAME
RUN sudo mkdir ~/.kube ~/.aws ~/.linuxbrew ~/.krew
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.2/zsh-in-docker.sh)" -- \
  -p git \
  -p 'history-substring-search'
RUN sudo cp /tmp/p10k.zsh ~/.p10k.zsh
RUN sudo chmod -R 777 ~/

RUN brew tap aws/tap ;\
  brew install eks-node-viewer \
  kube-ps1 \
  hubble \
  kubent

# Installing Krew
RUN ( \
  set -x; mkdir ~/.krew ; cd ~/.krew && \
  OS="$(uname | tr '[:upper:]' '[:lower:]')" && \
  ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" && \
  KREW="krew-${OS}_${ARCH}" && \
  pwd && \
  echo $KREW && \
  curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" && \
  tar zxvf "${KREW}.tar.gz" && \
  ./"${KREW}" install krew \
)
ENV PATH=/home/$USERNAME/.krew/bin:$PATH

# Install krew plugins
RUN kubectl krew install images \
  ktop \
  whoami \
  access-matrix \
  neat \
  tree \
  node-shell \
  tail \
  get-all \
  pod-dive \
  resource-capacity \
  df-pv \
  view-allocations \
  view-utilization \
  who-can \
  kubesec-scan \
  view-secret \
  iexec \
  spy \
  sniff \
  fuzzy \
  stern \
  status \
  podevents \
  ipick \
  pexec \
  exec-as \
  blame \
  custom-cols \
  explore \
  fields \
  ice

# install pulumi
#   python3 -m venv venv; \
#   venv/bin/pip3 install "pulumi>=3.0.0,<4.0.0" "pulumi-aws>=6.0.2,<7.0.0" "pulumi_mongodbatlas==3.7.2" "pulumi_mongodbatlas==3.7.2" "pulumi_kubernetes==4.0.3" "requests~=2.31.0"

# moved it here as below files are mostly modified
COPY aws-profiles /tmp/aws-profiles
COPY aws-credentials /tmp/aws-credentials
COPY zshrc /tmp/zshrc
RUN sudo cp /tmp/aws-profiles ~/.aws/config
RUN sudo cp /tmp/aws-credentials ~/.aws/credentials
RUN sudo cp /tmp/zshrc ~/.zshrc
RUN sudo chmod -R 777 ~/
